using System.Globalization;
using System.IO;
using System.Text;
using Labs.Engine.Models;

namespace Labs.Engine.Core;

/// <summary>Generates worker-compatible Python CV scripts from a CvScriptConfig.</summary>
public static class PythonGenerator
{
    /// <summary>Generates a Python script that works with worker.py's on_start/on_frame/on_stop API.</summary>
    public static string Generate(CvScriptConfig config)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"\"\"\"");
        sb.AppendLine($"Auto-generated CV script: {config.ScriptName}");
        sb.AppendLine($"Generated by CVCloud CV Builder");
        sb.AppendLine($"");
        sb.AppendLine($"Rules: {config.Rules.Count}");
        foreach (var rule in config.Rules)
            sb.AppendLine($"  - {rule.Name} ({rule.Type} -> {rule.ActionType})");
        sb.AppendLine($"\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import time");
        sb.AppendLine("import cv2");
        sb.AppendLine("import numpy as np");
        sb.AppendLine();

        // ---------------------------------------------------------------------------
        // Rule definitions as data
        // ---------------------------------------------------------------------------
        sb.AppendLine("# --- Detection Rules ---");
        sb.AppendLine("RULES = [");
        foreach (var rule in config.Rules)
        {
            sb.AppendLine("    {");
            sb.AppendLine($"        'name': {PyStr(rule.Name)},");
            sb.AppendLine($"        'type': '{rule.Type}',");
            sb.AppendLine($"        'action': '{rule.ActionType}',");
            sb.AppendLine($"        'region': ({F(rule.RegionX)}, {F(rule.RegionY)}, {F(rule.RegionW)}, {F(rule.RegionH)}),");

            switch (rule.Type)
            {
                case CvRuleType.ColorRange:
                    sb.AppendLine($"        'lower_hsv': np.array([{rule.LowerH}, {rule.LowerS}, {rule.LowerV}]),");
                    sb.AppendLine($"        'upper_hsv': np.array([{rule.UpperH}, {rule.UpperS}, {rule.UpperV}]),");
                    sb.AppendLine($"        'min_pixels': {rule.MinPixels},");
                    break;
                case CvRuleType.TemplateMatch:
                    sb.AppendLine($"        'template_path': {PyStr(rule.TemplatePath)},");
                    sb.AppendLine($"        'threshold': {F(rule.Threshold)},");
                    break;
                case CvRuleType.ContourDetect:
                    sb.AppendLine($"        'lower_hsv': np.array([{rule.LowerH}, {rule.LowerS}, {rule.LowerV}]),");
                    sb.AppendLine($"        'upper_hsv': np.array([{rule.UpperH}, {rule.UpperS}, {rule.UpperV}]),");
                    sb.AppendLine($"        'contour_w': ({rule.MinContourW}, {rule.MaxContourW}),");
                    sb.AppendLine($"        'contour_h': ({rule.MinContourH}, {rule.MaxContourH}),");
                    sb.AppendLine($"        'min_area': {rule.MinContourArea},");
                    break;
                case CvRuleType.PixelColor:
                    sb.AppendLine($"        'pixel_x': {rule.PixelX},");
                    sb.AppendLine($"        'pixel_y': {rule.PixelY},");
                    sb.AppendLine($"        'lower_hsv': np.array([{rule.LowerH}, {rule.LowerS}, {rule.LowerV}]),");
                    sb.AppendLine($"        'upper_hsv': np.array([{rule.UpperH}, {rule.UpperS}, {rule.UpperV}]),");
                    sb.AppendLine($"        'tolerance': {rule.ColorTolerance},");
                    break;
            }

            // Action config
            switch (rule.ActionType)
            {
                case CvActionType.PressButton:
                case CvActionType.HoldButton:
                case CvActionType.ReleaseButton:
                    sb.AppendLine($"        'button': {rule.ButtonIndex},");
                    sb.AppendLine($"        'hold_ms': {rule.HoldMs},");
                    break;
                case CvActionType.MoveStick:
                    sb.AppendLine($"        'stick_index': {rule.StickIndex},");
                    sb.AppendLine($"        'stick_value': {F(rule.StickValue)},");
                    break;
                case CvActionType.Combo:
                    sb.AppendLine($"        'combo': {PyStr(rule.ComboSequence)},");
                    break;
            }

            sb.AppendLine($"        'cooldown_ms': {rule.CooldownMs},");
            sb.AppendLine("    },");
        }
        sb.AppendLine("]");
        sb.AppendLine();

        // ---------------------------------------------------------------------------
        // State tracking
        // ---------------------------------------------------------------------------
        sb.AppendLine("# --- State ---");
        sb.AppendLine("templates = {}");
        sb.AppendLine("cooldowns = {}");
        sb.AppendLine("held_buttons = set()");
        sb.AppendLine("frame_count = 0");
        sb.AppendLine();

        // ---------------------------------------------------------------------------
        // on_start
        // ---------------------------------------------------------------------------
        sb.AppendLine("def on_start(config):");
        sb.AppendLine("    \"\"\"Load templates and initialize state.\"\"\"");
        sb.AppendLine("    for i, r in enumerate(RULES):");
        sb.AppendLine("        if r['type'] == 'TemplateMatch' and r.get('template_path'):");
        sb.AppendLine("            tpl = cv2.imread(r['template_path'])");
        sb.AppendLine("            if tpl is not None:");
        sb.AppendLine("                templates[i] = tpl");
        sb.AppendLine("                print(f\"[cv] Loaded template for rule '{r['name']}'\")");
        sb.AppendLine("            else:");
        sb.AppendLine("                print(f\"[cv] WARNING: template not found: {r['template_path']}\")");
        sb.AppendLine($"    print(f\"[cv] {config.ScriptName} started with {{len(RULES)}} rules\")");
        sb.AppendLine();

        // ---------------------------------------------------------------------------
        // Detection functions
        // ---------------------------------------------------------------------------
        sb.AppendLine("def detect_color_range(crop, r):");
        sb.AppendLine("    \"\"\"HSV color range detection. Returns (triggered, info_str).\"\"\"");
        sb.AppendLine("    hsv = cv2.cvtColor(crop, cv2.COLOR_BGR2HSV)");
        sb.AppendLine("    mask = cv2.inRange(hsv, r['lower_hsv'], r['upper_hsv'])");
        sb.AppendLine("    count = cv2.countNonZero(mask)");
        sb.AppendLine("    return count >= r['min_pixels'], f'{count}px'");
        sb.AppendLine();

        sb.AppendLine("def detect_template(crop, r, idx):");
        sb.AppendLine("    \"\"\"Template matching. Returns (triggered, info_str).\"\"\"");
        sb.AppendLine("    tpl = templates.get(idx)");
        sb.AppendLine("    if tpl is None: return False, 'no template'");
        sb.AppendLine("    th, tw = tpl.shape[:2]");
        sb.AppendLine("    if crop.shape[0] < th or crop.shape[1] < tw: return False, 'too small'");
        sb.AppendLine("    res = cv2.matchTemplate(crop, tpl, cv2.TM_CCOEFF_NORMED)");
        sb.AppendLine("    _, max_val, _, _ = cv2.minMaxLoc(res)");
        sb.AppendLine("    return max_val >= r['threshold'], f'{max_val:.2f}'");
        sb.AppendLine();

        sb.AppendLine("def detect_contour(crop, r):");
        sb.AppendLine("    \"\"\"HSV color + contour dimension detection (like Helios shot meter). Returns (triggered, info_str).\"\"\"");
        sb.AppendLine("    hsv = cv2.cvtColor(crop, cv2.COLOR_BGR2HSV)");
        sb.AppendLine("    mask = cv2.inRange(hsv, r['lower_hsv'], r['upper_hsv'])");
        sb.AppendLine("    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))");
        sb.AppendLine("    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)");
        sb.AppendLine("    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)");
        sb.AppendLine("    w_min, w_max = r['contour_w']");
        sb.AppendLine("    h_min, h_max = r['contour_h']");
        sb.AppendLine("    min_area = r['min_area']");
        sb.AppendLine("    for cnt in contours:");
        sb.AppendLine("        x, y, w, h = cv2.boundingRect(cnt)");
        sb.AppendLine("        area = cv2.contourArea(cnt)");
        sb.AppendLine("        if w_min <= w <= w_max and h_min <= h <= h_max and area >= min_area:");
        sb.AppendLine("            return True, f'{w}x{h} a={area:.0f}'");
        sb.AppendLine("    return False, f'{len(contours)} contours'");
        sb.AppendLine();

        sb.AppendLine("def detect_pixel_color(frame, r):");
        sb.AppendLine("    \"\"\"Single pixel color check. Returns (triggered, info_str).\"\"\"");
        sb.AppendLine("    fh, fw = frame.shape[:2]");
        sb.AppendLine("    px, py = min(r['pixel_x'], fw-1), min(r['pixel_y'], fh-1)");
        sb.AppendLine("    bgr = frame[py, px]");
        sb.AppendLine("    hsv_px = cv2.cvtColor(np.array([[bgr]], dtype=np.uint8), cv2.COLOR_BGR2HSV)[0][0]");
        sb.AppendLine("    lo, hi = r['lower_hsv'], r['upper_hsv']");
        sb.AppendLine("    match = all(lo[i] <= hsv_px[i] <= hi[i] for i in range(3))");
        sb.AppendLine("    return match, f'HSV={hsv_px}'");
        sb.AppendLine();

        // ---------------------------------------------------------------------------
        // on_frame — main detection + action loop
        // ---------------------------------------------------------------------------
        sb.AppendLine("def on_frame(frame, session_id, emit):");
        sb.AppendLine("    \"\"\"Process each frame: detect rules, execute actions, emit gamepad state.\"\"\"");
        sb.AppendLine("    global frame_count");
        sb.AppendLine("    frame_count += 1");
        sb.AppendLine("    fh, fw = frame.shape[:2]");
        sb.AppendLine("    now = time.monotonic()");
        sb.AppendLine();
        sb.AppendLine("    buttons = [False] * 17");
        sb.AppendLine("    axes = [0.0, 0.0, 0.0, 0.0]");
        sb.AppendLine();
        sb.AppendLine("    # Keep held buttons active");
        sb.AppendLine("    for btn_idx in held_buttons:");
        sb.AppendLine("        buttons[btn_idx] = True");
        sb.AppendLine();
        sb.AppendLine("    for i, r in enumerate(RULES):");
        sb.AppendLine("        # Crop region");
        sb.AppendLine("        rx, ry, rw, rh = r['region']");
        sb.AppendLine("        x1 = max(0, int(rx * fw))");
        sb.AppendLine("        y1 = max(0, int(ry * fh))");
        sb.AppendLine("        x2 = min(fw, int((rx + rw) * fw))");
        sb.AppendLine("        y2 = min(fh, int((ry + rh) * fh))");
        sb.AppendLine("        if x2 <= x1 or y2 <= y1: continue");
        sb.AppendLine("        crop = frame[y1:y2, x1:x2]");
        sb.AppendLine();
        sb.AppendLine("        # Detect");
        sb.AppendLine("        triggered = False");
        sb.AppendLine("        info = ''");
        sb.AppendLine("        rtype = r['type']");
        sb.AppendLine("        if rtype == 'ColorRange':");
        sb.AppendLine("            triggered, info = detect_color_range(crop, r)");
        sb.AppendLine("        elif rtype == 'TemplateMatch':");
        sb.AppendLine("            triggered, info = detect_template(crop, r, i)");
        sb.AppendLine("        elif rtype == 'ContourDetect':");
        sb.AppendLine("            triggered, info = detect_contour(crop, r)");
        sb.AppendLine("        elif rtype == 'PixelColor':");
        sb.AppendLine("            triggered, info = detect_pixel_color(frame, r)");
        sb.AppendLine();
        sb.AppendLine("        # Draw detection overlay");
        sb.AppendLine("        color = (0, 255, 0) if triggered else (60, 60, 60)");
        sb.AppendLine("        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 1)");
        sb.AppendLine("        cv2.putText(frame, f\"{r['name']}: {info}\", (x1+2, y1-4),");
        sb.AppendLine("                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, color, 1, cv2.LINE_AA)");
        sb.AppendLine();
        sb.AppendLine("        # Execute action if triggered and not in cooldown");
        sb.AppendLine("        if triggered:");
        sb.AppendLine("            cd = cooldowns.get(i, 0)");
        sb.AppendLine("            if now >= cd:");
        sb.AppendLine("                cooldowns[i] = now + r['cooldown_ms'] / 1000.0");
        sb.AppendLine("                action = r['action']");
        sb.AppendLine("                if action == 'PressButton':");
        sb.AppendLine("                    buttons[r['button']] = True");
        sb.AppendLine("                elif action == 'HoldButton':");
        sb.AppendLine("                    held_buttons.add(r['button'])");
        sb.AppendLine("                    buttons[r['button']] = True");
        sb.AppendLine("                elif action == 'ReleaseButton':");
        sb.AppendLine("                    held_buttons.discard(r['button'])");
        sb.AppendLine("                    buttons[r['button']] = False");
        sb.AppendLine("                elif action == 'MoveStick':");
        sb.AppendLine("                    axes[r['stick_index']] = r['stick_value']");
        sb.AppendLine("                elif action == 'Combo':");
        sb.AppendLine("                    # Parse combo: 'btn,hold;btn,hold;...'");
        sb.AppendLine("                    parts = r['combo'].split(';')");
        sb.AppendLine("                    for part in parts:");
        sb.AppendLine("                        tokens = part.strip().split(',')");
        sb.AppendLine("                        if len(tokens) >= 1:");
        sb.AppendLine("                            btn = int(tokens[0])");
        sb.AppendLine("                            buttons[btn] = True");
        sb.AppendLine();
        sb.AppendLine("    # Draw HUD");
        sb.AppendLine("    active = sum(1 for b in buttons if b)");
        sb.AppendLine($"    cv2.putText(frame, '{config.ScriptName} | ' + f'Frame {{frame_count}} | Buttons: {{active}}',");
        sb.AppendLine("                (5, 15), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (180, 180, 180), 1, cv2.LINE_AA)");
        sb.AppendLine();
        sb.AppendLine("    emit({'axes': axes, 'buttons': buttons})");
        sb.AppendLine();

        // ---------------------------------------------------------------------------
        // on_stop
        // ---------------------------------------------------------------------------
        sb.AppendLine("def on_stop():");
        sb.AppendLine("    held_buttons.clear()");
        sb.AppendLine($"    print(f'[cv] {config.ScriptName} stopped after {{frame_count}} frames')");

        // Write to Scripts folder
        var scriptsFolder = Path.Combine(AppContext.BaseDirectory, "Scripts");
        Directory.CreateDirectory(scriptsFolder);
        var safeName = config.ScriptName.Replace(" ", "_").Replace("/", "_").Replace("\\", "_");
        var outputPath = Path.Combine(scriptsFolder, $"{safeName}.py");
        File.WriteAllText(outputPath, sb.ToString());

        Console.WriteLine($"[PythonGenerator] Generated script: {outputPath}");
        return outputPath;
    }

    private static string F(double v) => v.ToString("F4", CultureInfo.InvariantCulture);
    private static string PyStr(string s) => $"r'{s.Replace("'", "\\'")}'";
}
