"""
Auto-generated CV script: NBA2K_ShotMeter
Generated by CVCloud CV Builder

Preset: NBA 2K Shot Meter Detection
Detects the purple/white shot meter bar and presses X to release at the right time.

Rules: 3
  - Purple Meter (ContourDetect -> PressButton)
  - White Flash (ColorRange -> PressButton)
  - Green Zone (ColorRange -> PressButton)
"""

import time
import cv2
import numpy as np

# --- Detection Rules ---
RULES = [
    {
        'name': 'Purple Meter',
        'type': 'ContourDetect',
        'action': 'PressButton',
        'region': (0.0026, 0.2315, 0.9974, 0.4815),
        'lower_hsv': np.array([130, 50, 150]),
        'upper_hsv': np.array([165, 255, 255]),
        'contour_w': (2, 30),
        'contour_h': (30, 220),
        'min_area': 50,
        'button': 2,
        'hold_ms': 80,
        'cooldown_ms': 500,
    },
    {
        'name': 'White Flash',
        'type': 'ColorRange',
        'action': 'PressButton',
        'region': (0.0026, 0.2315, 0.9974, 0.4815),
        'lower_hsv': np.array([0, 0, 230]),
        'upper_hsv': np.array([179, 30, 255]),
        'min_pixels': 300,
        'button': 2,
        'hold_ms': 50,
        'cooldown_ms': 500,
    },
    {
        'name': 'Green Zone',
        'type': 'ColorRange',
        'action': 'PressButton',
        'region': (0.0026, 0.2315, 0.9974, 0.4815),
        'lower_hsv': np.array([35, 100, 100]),
        'upper_hsv': np.array([85, 255, 255]),
        'min_pixels': 200,
        'button': 2,
        'hold_ms': 50,
        'cooldown_ms': 600,
    },
]

# --- State ---
templates = {}
cooldowns = {}
held_buttons = set()
frame_count = 0


def on_start(config):
    """Load templates and initialize state."""
    print(f"[cv] NBA2K Shot Meter preset started with {len(RULES)} rules")


def detect_color_range(crop, r):
    hsv = cv2.cvtColor(crop, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, r['lower_hsv'], r['upper_hsv'])
    count = cv2.countNonZero(mask)
    return count >= r['min_pixels'], f'{count}px'


def detect_contour(crop, r):
    hsv = cv2.cvtColor(crop, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, r['lower_hsv'], r['upper_hsv'])
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    w_min, w_max = r['contour_w']
    h_min, h_max = r['contour_h']
    min_area = r['min_area']
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        area = cv2.contourArea(cnt)
        if w_min <= w <= w_max and h_min <= h <= h_max and area >= min_area:
            return True, f'{w}x{h} a={area:.0f}'
    return False, f'{len(contours)} contours'


def on_frame(frame, session_id, emit):
    global frame_count
    frame_count += 1
    fh, fw = frame.shape[:2]
    now = time.monotonic()

    buttons = [False] * 17
    axes = [0.0, 0.0, 0.0, 0.0]

    for btn_idx in held_buttons:
        buttons[btn_idx] = True

    for i, r in enumerate(RULES):
        rx, ry, rw, rh = r['region']
        x1 = max(0, int(rx * fw))
        y1 = max(0, int(ry * fh))
        x2 = min(fw, int((rx + rw) * fw))
        y2 = min(fh, int((ry + rh) * fh))
        if x2 <= x1 or y2 <= y1:
            continue
        crop = frame[y1:y2, x1:x2]

        triggered = False
        info = ''
        if r['type'] == 'ColorRange':
            triggered, info = detect_color_range(crop, r)
        elif r['type'] == 'ContourDetect':
            triggered, info = detect_contour(crop, r)

        color = (0, 255, 0) if triggered else (60, 60, 60)
        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 1)
        cv2.putText(frame, f"{r['name']}: {info}", (x1+2, y1-4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.35, color, 1, cv2.LINE_AA)

        if triggered:
            cd = cooldowns.get(i, 0)
            if now >= cd:
                cooldowns[i] = now + r['cooldown_ms'] / 1000.0
                buttons[r['button']] = True

    active = sum(1 for b in buttons if b)
    cv2.putText(frame, f'2K Meter | Frame {frame_count} | Buttons: {active}',
                (5, 15), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (180, 180, 180), 1, cv2.LINE_AA)

    emit({'axes': axes, 'buttons': buttons})


def on_stop():
    held_buttons.clear()
    print(f'[cv] NBA2K Shot Meter stopped after {frame_count} frames')
